// <auto-generated />
using GCPTestAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GCPTestAPI.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20201126183758_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GCPTestAPI.PointValue", b =>
                {
                    b.Property<double>("Real")
                        .HasColumnType("float");

                    b.Property<double>("Imaginary")
                        .HasColumnType("float");

                    b.Property<int>("Iterations")
                        .HasColumnType("int");

                    b.HasKey("Real", "Imaginary");

                    b.ToTable("PointValues");
                });
#pragma warning restore 612, 618
        }
    }
}
