runtime: aspnetcore

env: flex

manual_scaling:

  instances: 1

resources:

  cpu: 1

  memory_gb: 0.5

  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: gpc-dotnetcore-viability-test:europe-west6:testsqldb=tcp:1470

env_variables:
  ASPNETCORE_ENVIRONMENT: Flex